- headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java
Versions tags on resources should be a map not a "version" as defined elsewhere within a pipeline.
[Reference](http://concourse.ci/single-page.html#image-resource-version):
> ```
> version: object
> ```
> Optional. A specific version of the resource to fetch. This should be a map with string keys and values. If not specified, the latest version will be fetched.
Example:
```
- get: cf-deployment-git
version: { ref: ((cf_deployment_commit_ref)) }
```
> update resource version to take a map string->string

- vscode-extensions/vscode-spring-boot/package.json
Of course, it is for authors to name their creation.
Nevertheless, there are now 2 VSCode extension with name "Spring Boot Support".  
And also current published version is the same version number as previous obsolete: 0.1.4  
That make confusion.
Also Tools is used in https://spring.io/tools4
and has been unique word on Eclipse marketplace.
> VSCode - Name wording: Tools instead of Support

- eclipse-language-servers/org.springframework.tooling.ls.eclipse.gotosymbol/src/org/springframework/tooling/ls/eclipse/gotosymbol/handlers/GotoSymbolHandler.java
Got to Symbol in Workspace shows by default. Cmd-6 or Ctrl-6 to toggle between workspace and file symbols
> PT #160634135: Show symbols in workspace by default

- eclipse-language-servers/org.springframework.tooling.ls.eclipse.gotosymbol/src/org/springframework/tooling/ls/eclipse/gotosymbol/dialogs/InProjectSymbolsProvider.java
- eclipse-language-servers/org.springframework.tooling.ls.eclipse.gotosymbol/src/org/springframework/tooling/ls/eclipse/gotosymbol/dialogs/InWorkspaceSymbolsProvider.java
- eclipse-language-servers/org.springframework.tooling.ls.eclipse.gotosymbol/src/org/springframework/tooling/ls/eclipse/gotosymbol/handlers/GotoSymbolHandler.java
Add new provider which will filter symbols for the current selected
resource's project in GoTo Symbol dialog.
> Fix #173 : Add support for filtering project symbols

- headless-services/commons/commons-maven/src/test/resources/maven-config/settings.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
> URL Cleanup

- idea-extensions/idea-boot-java/.gitignore
- idea-extensions/idea-boot-java/build.gradle
- idea-extensions/idea-boot-java/gradlew
- idea-extensions/idea-boot-java/gradlew.bat
- idea-extensions/idea-boot-java/settings.gradle
- idea-extensions/idea-boot-java/src/org/spring/tools/boot/java/ls/BootJavaPreloadingActivity.scala
When the server jar is inside classpath the final packaged plugin cause
the server jar to be packaged inside the plugin jar which cause it to
fail. Now the server jar is packed outside with the support of gradle.
Signed-off-by: gayanper <gayanper@gmail.com>
> gradlize and add support for better language server loading

- eclipse-distribution/pom.xml
- eclipse-language-servers/pom.xml
- headless-services/jdt-ls-extension/pom.xml
I stumbled upon the prerequisites section in Maven while trying to build sts4 (which I didn't success with). Prerequisites should not be used for Maven 3 and is only valid for Maven plugins. It usually results in warnings while building a project.
The maven-enforcer-plugin can be used to enforce a Maven version.
> Remove prerequisites from Maven pom files

- headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java
- headless-services/concourse-language-server/src/test/java/org/springframework/ide/vscode/concourse/ConcourseEditorTest.java
Currently the language server throws an error like
"Expected string, got sequence" when you use yaml
as a default for a parameter in a task yaml.
See added test for an example that triggers the
behavior.
> Fix concourse task schema

- eclipse-language-servers/org.springframework.tooling.boot.ls/plugin.xml
Marked the SpringBootJavaCompletionProposalComputer as requiresUIThread
= false so that the completions can be run asyncly.
This will make the new java async support to work even when STS4 tooling is installed.
> Add support for async completions in 4.15

- nodejs-packages/jvm-launch-utils/src/jvm-util.ts
I got the same error as in #392 and tracked it back to the `findJdk` method. It calls `isJdk` on the resolved value from `findJvm`, which is null when no JVM was found.
I tested the change with the vs code plugin and got the expected "Couldn't locate java in $JAVA_HOME or $PATH" error message instead of the null reference.
I didn't test other projects using the jvm-launch-utils, because I don't have a setup for them.
> Fix null reference when no JVM was found

- vscode-extensions/vscode-concourse/README.md
- vscode-extensions/vscode-concourse/package.json
> support pipeline directory as well see

- headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java
- headless-services/concourse-language-server/src/main/resources/desc/Display/background_image.md
- headless-services/concourse-language-server/src/main/resources/desc/Pipeline/display.md
- headless-services/concourse-language-server/src/test/java/org/springframework/ide/vscode/concourse/ConcourseEditorTest.java
In Concourse 6.6, a feature was introduced to allow pipeline developers
to set custom background images to their pipelines. This commit adds
support for that field to the language server.
> Add display property to pipeline schema

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessCommandHandler.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorService.java
- vscode-extensions/vscode-spring-boot/lib/Main.ts
- vscode-extensions/vscode-spring-boot/lib/api.d.ts
- vscode-extensions/vscode-spring-boot/lib/apiManager.ts
- vscode-extensions/vscode-spring-boot/lib/notification.ts
Currently sts-vscode expose its language client to other extensions. In this PR, besides the language client instance, I also expose some APIs for downstream extension to easily get live process data. (see `api.d.ts`)
Downstream extension can now listen to events when live connection is connected/disconnected, and decides to fetch live data using the API.
> add extension APIs to get live data

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessCommandHandler.java
- vscode-extensions/vscode-spring-boot/lib/apiManager.ts
A patch for PR #751, otherwise it won't work. Fixing two problems:
- inconsistent name of argument between API definition and implmentation.
- didn't return the result in `getLiveProcessData`
> sts-vscode: fix extension api implementation

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessCommandHandler.java
- vscode-extensions/vscode-spring-boot/lib/api.d.ts
- vscode-extensions/vscode-spring-boot/lib/apiManager.ts
Follow up from: https://github.com/spring-projects/sts4/pull/751#issuecomment-1089745171
This adds one extra function to the api to retrieve the current list of connected processes.
> Add 'listConnectedProcesses' to public api

- headless-services/commons/commons-lsp-extensions/src/main/java/org/springframework/ide/vscode/commons/protocol/LiveProcessSummary.java
- headless-services/commons/commons-lsp-extensions/src/main/java/org/springframework/ide/vscode/commons/protocol/STS4LanguageClient.java
- headless-services/commons/language-server-test-harness/src/main/java/org/springframework/ide/vscode/languageserver/testharness/LanguageServerHarness.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/ProcessType.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessCommandHandler.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnector.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorLocal.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorOverHttp.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorOverJMX.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorRemote.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessLiveData.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessLiveDataExtractorOverHttp.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessLiveDataExtractorOverJMX.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessLiveDataProvider.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/project/harness/SpringProcessLiveDataBuilder.java
- vscode-extensions/vscode-spring-boot/lib/api.d.ts
- vscode-extensions/vscode-spring-boot/lib/apiManager.ts
- vscode-extensions/vscode-spring-boot/lib/notification.ts
Events now include some extra information instead of just processKey.
As per discussion in slack https://vmware.slack.com/archives/C035GS8FD4J/p1651815875749779
@Eskibear ... please have a look. See if it looks like what you expected / need.
@BoykoAlex  Also interested to hear your opinion if you are so inclined.
> Refine api for connected process listeners

- headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImagePutParams/bump_aliases.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImagePutParams/version.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_access_key_id.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_region.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_role_arn.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_role_arns.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_secret_access_key .md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/aws_session_token.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/ca_certs.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/insecure.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/semver_constraint.md
- headless-services/concourse-language-server/src/main/resources/desc/RegistryImageSource/variant.md
Update Concourse `registry-image` resource schema to match [`concourse/registry-image-resource`](https://github.com/concourse/registry-image-resource/blob/671c7bcae57f48111cd7fd755eea7b72553fb44f/README.md)
**Sources:**
- [Source Configuration](https://github.com/concourse/registry-image-resource/blob/671c7bcae57f48111cd7fd755eea7b72553fb44f/README.md#source-configuration)
- [`get` Step `params`](https://github.com/concourse/registry-image-resource/blob/671c7bcae57f48111cd7fd755eea7b72553fb44f/README.md#get-step-params)
- [`put` Steps `params`](https://github.com/concourse/registry-image-resource/blob/671c7bcae57f48111cd7fd755eea7b72553fb44f/README.md#put-steps-params)
> Update Concourse registry-image schema

- vscode-extensions/vscode-concourse/README.md
- vscode-extensions/vscode-concourse/package.json
Some people write .yml, some write .yaml. Both pipeline.yml and pipeline.yaml behave the same way, so highlight them both as Concourse pipelines & tasks.
Added because my organization uses pipeline.yaml consistently, so probably other people do too.
1. create a file `~/tmp/pipeline.yaml`
2. run extension
3. open terminal
4. `code ~/tmp/pipeline.yaml`
5. look at the bottom to see if it says "Concourse Pipeline" or "YAML"
| before | after |
| --- | --- |
| <img width="731" alt="image" src="https://user-images.githubusercontent.com/3344958/189281019-147ef48a-2cb5-4578-a23b-d7b9280af7b8.png"> | <img width="731" alt="image" src="https://user-images.githubusercontent.com/3344958/189281005-7abb005d-91d4-4c8b-96f4-4a3116cc72d2.png"> |
> vscode-concourse: support both .yml and .yaml files

- vscode-extensions/boot-dev-pack/package.json
VS Code now recommends boot-dev-pack for spring developers. Here to add a shortcut to dashboard for exposure.
> Add shortcut to dashboard

- vscode-extensions/boot-dev-pack/package.json
Changes:
- Use "Spring Initilizr" instead of "Spring" to locate the create project command, otherwise there would be lots of other Spring related commands on the list.
- remove "in VS Code" and duplicate "Spring Boot" for simplicity, as the section is all about that, which should be safe and won't cause confusion.
> update walkthrough about creating projects

- eclipse-language-servers/org.springframework.tooling.boot.ls/src/org/springframework/tooling/boot/ls/BootProjectTester.java
Added a check that the JDT project uses to confirm the project is a Java project. JavaCore#create will return an object even if the project isn't a Java project and is therefore insufficient. Bring up the context menu on non Java projects to the see the JME logged without this fix (possibly other repercussions as well).
> Fix JavaModelException with non-Java projects

- eclipse-extensions/org.springframework.ide.eclipse.beans.ui.live/src/org/springframework/ide/eclipse/beans/ui/live/utils/JdtUtils.java
- eclipse-language-servers/org.springsource.ide.eclipse.commons.core/src/org/springsource/ide/eclipse/commons/core/JdtUtils.java
Due to [these changes](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/4869388c3389ea51ff492a1129f1c442521c18da), this cast will now result in a ClassCastException.
It may not be too easy to reproduce this, though you can see from the code changes that a CCE would be expected. The following steps seem to trigger it.
1. Create a simple Java project using the Java project wizard.
2. Convert to faceted form using the context menu item.
3. Open the project's properties and go to the Project Facets property page, and add the Web Fragment facet. Apply the change. 
Usually at this point you should see the CCE in the error log. In some cases, adding the Dynamic Web Project facet would do it.
I realize this isn't a "Spring" use case, but it was one of the easiest ways I could find to …
> Fixes CCE: JavaNature cannot be cast to IJavaProject

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/BootJavaCompletionEngineConfigurer.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/Annotations.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/contextconfiguration/ContextConfigurationProcessor.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/java/contextconfiguration/test/ContextConfigurationCompletionTest.java
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-contextconfiguration/mvnw
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-contextconfiguration/mvnw.cmd
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-contextconfiguration/pom.xml
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-contextconfiguration/src/main/java/org/test/TestAnnotationsContextConfigurationApplication.java
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-contextconfiguration/src/main/java/org/test/TestContextConfigurationCompletion.java
Added content-assist feature to auto complete xml files from the classpath for @ContextConfiguration annotations
Issue: #650
> Add file completion from classpath for @ContextConfiguration

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/contextconfiguration/ContextConfigurationProcessor.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/java/contextconfiguration/test/ContextConfigurationCompletionTest.java
Fixed missing proposal if the prefix starts with "/" for @ContextConfiguration annotations
Issue: #650
> Fix missing proposal if the prefix starts with "/" for @ContextConfiguration

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/BootJavaCompletionEngineConfigurer.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/BootLanguageServerBootApp.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/conditionalonresource/ConditionalOnResourceDefinitionProvider.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/conditionalonresource/ConditionalOnResourceProcessor.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/java/conditionalonresource/test/ConditionalOnResourceCompletionTest.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/java/conditionalonresource/test/ConditionalOnResourceDefinitionProviderTest.java
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-conditionalonresource/mvnw
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-conditionalonresource/mvnw.cmd
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-conditionalonresource/pom.xml
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-conditionalonresource/src/main/java/org/test/TestAnnotationsConditionalOnResourceApplication.java
- headless-services/spring-boot-language-server/src/test/resources/test-projects/test-annotation-conditionalonresource/src/main/java/org/test/TestConditionalOnResourceCompletion.java
> GH-1310: Add support for ConditionalOnResource annotation

- eclipse-extensions/org.springframework.ide.eclipse.boot.launch/src/org/springframework/ide/eclipse/boot/launch/AbstractBootLaunchConfigurationDelegate.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/properties/PropertiesToYamlCommandTest.java
Correct typo from 'propeties' to 'properties'.
> Correct typo from 'propeties' to 'properties'

- headless-services/commons/commons-language-server/src/main/java/org/springframework/ide/vscode/commons/languageserver/util/SimpleLanguageServer.java
- headless-services/commons/commons-language-server/src/main/java/org/springframework/ide/vscode/commons/languageserver/util/SimpleTextDocumentService.java
- headless-services/commons/commons-util/src/main/java/org/springframework/ide/vscode/commons/util/text/LazyTextDocument.java
- headless-services/commons/commons-util/src/main/java/org/springframework/ide/vscode/commons/util/text/TextDocument.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/BootLanguageServerInitializer.java
Fixes #1387 
Validate closed docs that were not saved.
> Validate non-saved docs on close

- headless-services/commons/commons-language-server/src/main/java/org/springframework/ide/vscode/commons/languageserver/LanguageServerRunner.java
- headless-services/commons/commons-lsp-extensions/src/main/java/org/springframework/ide/vscode/commons/RuntimeTypeAdapterFactory.java
- headless-services/commons/commons-lsp-extensions/src/main/java/org/springframework/ide/vscode/commons/protocol/spring/Bean.java
- headless-services/commons/commons-lsp-extensions/src/main/java/org/springframework/ide/vscode/commons/protocol/spring/InjectionPoint.java
- headless-services/commons/language-server-starter/src/main/java/org/springframework/ide/vscode/languageserver/starter/LanguageServerRunnerAutoConf.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/BootLanguageServerBootApp.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/app/CommandsConfig.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/index/cache/IndexCacheOnDiscDeltaBased.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/commands/SpringIndexCommands.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/cron/JdtCronVisitorUtils.java
- headless-services/spring-boot-language-server/src/test/java/org/springframework/ide/vscode/boot/index/test/SpringMetamodelIndexTest.java
- vscode-extensions/vscode-spring-boot/lib/Main.ts
- vscode-extensions/vscode-spring-boot/lib/api.d.ts
- vscode-extensions/vscode-spring-boot/lib/apiManager.ts
- vscode-extensions/vscode-spring-boot/lib/explorer/explorer-tree-provider.ts
- vscode-extensions/vscode-spring-boot/lib/explorer/nodes.ts
- vscode-extensions/vscode-spring-boot/lib/explorer/structure-tree-manager.ts
- vscode-extensions/vscode-spring-boot/package.json
- Serialization for index elements via `RuntimeTypeAdapterFactory` borrowed from **gson-extras**
- Initial implementation of the structure view in VSCode
> Structure view

- eclipse-language-servers/org.springsource.ide.eclipse.commons.frameworks.core/src/org/springsource/ide/eclipse/commons/frameworks/core/util/FileUtil.java
This PR refactor createTempDirectory method in FileUtil.java to use java.nio.file.Files. 
The previous approach required manual handling of temporary file deletion and directory creation, could also pose a security vulnerability (CWE-379). The NIO-based method is more atomic and cleaner.
Changes made:
- Replaced use of `File.createTempFile`, `delete()`, and `mkdirs()` with `Files.createTempDirectory`.
- Updated imports to use `java.nio.file.Path` and `Files`.
References 
https://github.com/UniversaBlockchain/universa/commit/1e34b1804842a7a2ba27fa9f4210a6fcb340d517
https://www.cve.org/CVERecord?id=CVE-2022-27772
Thanks for taking the time to review!
> Refactor createTempDirectory method to use java.nio.file.Files

- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/commands/ApplicationModule.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/commands/ApplicationModulesLabelProvider.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/commands/ApplicationModulesStructureProvider.java
- headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/commands/ModulithStructureView.java
We now allow disabling the named interfaces grouping via a disable-named-interfaces system property for the Language Server. If this is activated, the type labels are now additionally decorated with an "API" / "internal" extension to indicate, whether they are accessible to other modules.
> Allow disabling named interface grouping via system property.
